# Generated by Django 4.1.1 on 2022-10-01 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_company_foundation_alter_company_name_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.company'),
        ),
    ]
