# Generated by Django 4.1.1 on 2022-10-01 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_mark_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='mark_date',
            field=models.DateTimeField(default=datetime.date.today, null=True),
        ),
    ]
